# Generated by Django 4.2.5 on 2023-09-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_gifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feathers',
            field=models.IntegerField(default=0),
        ),
    ]
