# Generated by Django 4.2.5 on 2023-11-26 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Edit to add name', max_length=45)),
                ('level', models.IntegerField(default=1)),
                ('health', models.IntegerField(default=1)),
                ('energy', models.IntegerField(default=1)),
                ('happiness', models.IntegerField(default=1)),
                ('max_health', models.IntegerField(default=1)),
                ('max_energy', models.IntegerField(default=1)),
                ('max_happiness', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Celestial',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('image', models.CharField(default='pets/css/images/celestial-dragon.png', editable=False, max_length=150)),
                ('avatar', models.CharField(default='pets/css/images/celestial-dragon-avatar.png', editable=False, max_length=150)),
                ('pet_type', models.CharField(default='Celestial Dragon', editable=False, max_length=45)),
                ('experience', models.IntegerField(default=0)),
                ('xp_to_lvl', models.IntegerField(default=120)),
            ],
            bases=('pets.pet',),
        ),
        migrations.CreateModel(
            name='Glorb',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('image', models.CharField(default='pets/css/images/glorb.png', editable=False, max_length=150)),
                ('avatar', models.CharField(default='pets/css/images/glorb-avatar.png', editable=False, max_length=150)),
                ('pet_type', models.CharField(default='Glorb', editable=False, max_length=45)),
                ('experience', models.IntegerField(default=5)),
                ('xp_to_lvl', models.IntegerField(default=10)),
            ],
            bases=('pets.pet',),
        ),
        migrations.CreateModel(
            name='GreenDragon',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('image', models.CharField(default='pets/css/images/green-dragon.png', editable=False, max_length=150)),
                ('avatar', models.CharField(default='pets/css/images/green-dragon-avatar.png', editable=False, max_length=150)),
                ('pet_type', models.CharField(default='Green Dragon', editable=False, max_length=45)),
                ('experience', models.IntegerField(default=0)),
                ('xp_to_lvl', models.IntegerField(default=10)),
            ],
            bases=('pets.pet',),
        ),
        migrations.CreateModel(
            name='Griffin',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('image', models.CharField(default='pets/css/images/griffin.png', editable=False, max_length=150)),
                ('avatar', models.CharField(default='pets/css/images/griffin-avatar.png', editable=False, max_length=150)),
                ('pet_type', models.CharField(default='Griffin', editable=False, max_length=45)),
                ('experience', models.IntegerField(default=0)),
                ('xp_to_lvl', models.IntegerField(default=15)),
            ],
            bases=('pets.pet',),
        ),
        migrations.CreateModel(
            name='Hydra',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('image', models.CharField(default='pets/css/images/hydra.png', editable=False, max_length=150)),
                ('avatar', models.CharField(default='pets/css/images/hydra-avatar.png', editable=False, max_length=150)),
                ('pet_type', models.CharField(default='Hydra', editable=False, max_length=45)),
                ('experience', models.IntegerField(default=0)),
                ('xp_to_lvl', models.IntegerField(default=40)),
            ],
            bases=('pets.pet',),
        ),
        migrations.CreateModel(
            name='Kraken',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('image', models.CharField(default='pets/css/images/kraken.png', editable=False, max_length=150)),
                ('avatar', models.CharField(default='pets/css/images/kraken-avatar.png', editable=False, max_length=150)),
                ('pet_type', models.CharField(default='Kraken', editable=False, max_length=45)),
                ('experience', models.IntegerField(default=0)),
                ('xp_to_lvl', models.IntegerField(default=25)),
            ],
            bases=('pets.pet',),
        ),
        migrations.CreateModel(
            name='Moogle',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('image', models.CharField(default='pets/css/images/moogle.png', editable=False, max_length=150)),
                ('avatar', models.CharField(default='pets/css/images/moogle-avatar.png', editable=False, max_length=150)),
                ('pet_type', models.CharField(default='Moogle', editable=False, max_length=45)),
                ('experience', models.IntegerField(default=5)),
                ('xp_to_lvl', models.IntegerField(default=12)),
            ],
            bases=('pets.pet',),
        ),
        migrations.CreateModel(
            name='MythicGriffin',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('image', models.CharField(default='pets/css/images/mythic-griffin.png', editable=False, max_length=150)),
                ('avatar', models.CharField(default='pets/css/images/mythic-griffin-avatar.png', editable=False, max_length=150)),
                ('pet_type', models.CharField(default='Mythic Griffin', editable=False, max_length=45)),
                ('experience', models.IntegerField(default=0)),
                ('xp_to_lvl', models.IntegerField(default=50)),
            ],
            bases=('pets.pet',),
        ),
        migrations.CreateModel(
            name='RedDragon',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('image', models.CharField(default='pets/css/images/red-dragon.png', editable=False, max_length=150)),
                ('avatar', models.CharField(default='pets/css/images/red-dragon-avatar.png', editable=False, max_length=150)),
                ('pet_type', models.CharField(default='Red Dragon', editable=False, max_length=45)),
                ('experience', models.IntegerField(default=0)),
                ('xp_to_lvl', models.IntegerField(default=10)),
            ],
            bases=('pets.pet',),
        ),
        migrations.CreateModel(
            name='Siren',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('image', models.CharField(default='pets/css/images/cat-siren.png', editable=False, max_length=150)),
                ('avatar', models.CharField(default='pets/css/images/cat-siren-avatar.png', editable=False, max_length=150)),
                ('pet_type', models.CharField(default='Cat-siren', editable=False, max_length=45)),
                ('experience', models.IntegerField(default=9)),
                ('xp_to_lvl', models.IntegerField(default=10)),
            ],
            bases=('pets.pet',),
        ),
        migrations.CreateModel(
            name='Snek',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('image', models.CharField(default='pets/css/images/snek.png', editable=False, max_length=150)),
                ('avatar', models.CharField(default='pets/css/images/snek-avatar.png', editable=False, max_length=150)),
                ('pet_type', models.CharField(default='Snek', editable=False, max_length=45)),
                ('experience', models.IntegerField(default=0)),
                ('xp_to_lvl', models.IntegerField(default=10)),
            ],
            bases=('pets.pet',),
        ),
        migrations.CreateModel(
            name='TartCat',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('image', models.CharField(default='pets/css/images/tart-cat.png', editable=False, max_length=150)),
                ('avatar', models.CharField(default='pets/css/images/tart-cat-avatar.png', editable=False, max_length=150)),
                ('pet_type', models.CharField(default='Tart-cat', editable=False, max_length=45)),
                ('experience', models.IntegerField(default=9)),
                ('xp_to_lvl', models.IntegerField(default=10)),
            ],
            bases=('pets.pet',),
        ),
    ]
