# Generated by Django 4.2.5 on 2023-09-20 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Edit to add name', max_length=45)),
                ('level', models.IntegerField(default=1)),
                ('health', models.IntegerField(default=1)),
                ('energy', models.IntegerField(default=1)),
                ('happiness', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Glorb',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet')),
                ('max_health', models.IntegerField(default=4)),
                ('max_energy', models.IntegerField(default=7)),
                ('max_happiness', models.IntegerField(default=7)),
                ('experience', models.IntegerField(default=5)),
                ('xp_to_lvl', models.IntegerField(default=10)),
            ],
            bases=('pets.pet',),
        ),
    ]
