# Generated by Django 4.2.5 on 2023-09-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glorb',
            name='max_energy',
        ),
        migrations.RemoveField(
            model_name='glorb',
            name='max_happiness',
        ),
        migrations.RemoveField(
            model_name='glorb',
            name='max_health',
        ),
        migrations.AddField(
            model_name='glorb',
            name='pet_type',
            field=models.CharField(default='Glorb', editable=False, max_length=45),
        ),
        migrations.AddField(
            model_name='pet',
            name='max_energy',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='max_happiness',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='max_health',
            field=models.IntegerField(default=1),
        ),
    ]
