# Generated by Django 4.2.5 on 2023-09-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_celestial_greendragon_griffin_hydra_kraken_moogle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glorb',
            name='avatar',
            field=models.CharField(default='pets/css/images/glorb-avatar.png', editable=False, max_length=150),
        ),
    ]
