# Generated by Django 4.2.5 on 2023-09-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_glorb_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='celestial',
            name='avatar',
            field=models.CharField(default='pets/css/images/celestial-dragon-avatar.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='celestial',
            name='image',
            field=models.CharField(default='pets/css/images/celestial-dragon.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='glorb',
            name='image',
            field=models.CharField(default='pets/css/images/glorb.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='greendragon',
            name='avatar',
            field=models.CharField(default='pets/css/images/green-dragon-avatar.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='greendragon',
            name='image',
            field=models.CharField(default='pets/css/images/green-dragon.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='griffin',
            name='avatar',
            field=models.CharField(default='pets/css/images/griffin-avatar.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='griffin',
            name='image',
            field=models.CharField(default='pets/css/images/griffin.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='hydra',
            name='avatar',
            field=models.CharField(default='pets/css/images/hydra-avatar.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='hydra',
            name='image',
            field=models.CharField(default='pets/css/images/hydra.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='kraken',
            name='avatar',
            field=models.CharField(default='pets/css/images/kraken-avatar.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='kraken',
            name='image',
            field=models.CharField(default='pets/css/images/kraken.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='moogle',
            name='avatar',
            field=models.CharField(default='pets/css/images/moogle-avatar.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='moogle',
            name='image',
            field=models.CharField(default='pets/css/images/moogle.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='mythicgriffin',
            name='avatar',
            field=models.CharField(default='pets/css/images/mythic-griffin-avatar.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='mythicgriffin',
            name='image',
            field=models.CharField(default='pets/css/images/mythic-griffin.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='reddragon',
            name='avatar',
            field=models.CharField(default='pets/css/images/red-dragon-avatar.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='reddragon',
            name='image',
            field=models.CharField(default='pets/css/images/red-dragon.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='siren',
            name='avatar',
            field=models.CharField(default='pets/css/images/cat-siren-avatar.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='siren',
            name='image',
            field=models.CharField(default='pets/css/images/cat-siren.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='snek',
            name='avatar',
            field=models.CharField(default='pets/css/images/snek-avatar.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='snek',
            name='image',
            field=models.CharField(default='pets/css/images/snek.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='tartcat',
            name='avatar',
            field=models.CharField(default='pets/css/images/tart-cat-avatar.png', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='tartcat',
            name='image',
            field=models.CharField(default='pets/css/images/tart-cat.png', editable=False, max_length=150),
        ),
    ]
